site_name: 信管专业课程笔记
site_url: https://0824-maker.github.io/note-website/
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
nav:
  - 首页: index.md
  - 通用英语三: english.md
  - 计算机程序设计原理: jsj.md
  - 毛概: mg.md
  - 信息网络化基础: xxwlh.md
 
